# Generated by Django 3.1.6 on 2021-03-25 17:02
from datetime import datetime, timedelta

from django.db import migrations, models


def set_my_defaults(apps, schema_editor):
    Product = apps.get_model('main', 'Product')
    for product in Product.objects.all().iterator():
        product.updated_as = datetime.now() + timedelta(days=product.some_other_field)
        product.save()

def reverse_func(apps, schema_editor):
    pass  # code for reverting migration, if any


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.RunPython(set_my_defaults, reverse_func),
        migrations.AlterField(
            model_name='product',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
