# Generated by Django 3.1.6 on 2021-03-28 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210327_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='how_old',
            field=models.IntegerField(null=True),
        ),
    ]
