# Generated by Django 3.1.7 on 2021-04-28 07:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=' ', size=None),
        ),
    ]
