# Generated by Django 3.1.7 on 2021-05-18 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_productviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tags_array',
        ),
    ]
