# Generated by Django 3.1.6 on 2021-03-25 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20210325_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
