# Generated by Django 3.1.6 on 2021-03-25 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20210325_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='update',
        ),
    ]
